@application/init.sql
@application/set_environment.sql
@application/delete_application.sql
@application/ui_types.sql
@application/create_application.sql
@application/shared_components/navigation/lists.sql
@application/shared_components/files.sql
@application/plugin_settings.sql
@application/shared_components/security/authorizations.sql
@application/shared_components/navigation/navigation_bar.sql
@application/shared_components/logic/application_processes.sql
@application/shared_components/logic/application_items.sql
@application/shared_components/logic/application_computations.sql
@application/shared_components/navigation/tabs/standard.sql
@application/shared_components/navigation/tabs/parent.sql
@application/shared_components/user_interface/lovs.sql
@application/shared_components/navigation/trees.sql
@application/pages/page_groups.sql
@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@application/shared_components/user_interface/templates/page.sql
@application/shared_components/user_interface/templates/button.sql
@application/shared_components/user_interface/templates/region.sql
@application/shared_components/user_interface/templates/list.sql
@application/shared_components/user_interface/templates/report.sql
@application/shared_components/user_interface/templates/label.sql
@application/shared_components/user_interface/templates/breadcrumb.sql
@application/shared_components/user_interface/templates/popuplov.sql
@application/shared_components/user_interface/templates/calendar.sql
@application/shared_components/user_interface/themes.sql
@application/shared_components/user_interface/theme_style.sql
@application/shared_components/user_interface/theme_files.sql
@application/shared_components/user_interface/theme_display_points.sql
@application/shared_components/user_interface/template_opt_groups.sql
@application/shared_components/user_interface/template_options.sql
@application/shared_components/logic/build_options.sql
@application/shared_components/globalization/language.sql
@application/shared_components/globalization/messages.sql
@application/shared_components/globalization/dyntranslations.sql
@application/shared_components/user_interface/shortcuts.sql
@application/shared_components/security/authentications.sql
@application/ui_types.sql
@application/user_interfaces.sql
@application/user_interfaces/combined_files.sql
@application/pages/page_00001.sql
@application/pages/page_00002.sql
@application/pages/page_00003.sql
@application/pages/page_00004.sql
@application/pages/page_00005.sql
@application/pages/page_00006.sql
@application/pages/page_00007.sql
@application/pages/page_00101.sql
@application/end_environment.sql
